INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BJZ',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BJZ',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BJZ',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BFS',1,3,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,4,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,4,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',1,4,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,4,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,4,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,4,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',2,4,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SXF',3,4,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',1,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',2,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BLQ',2,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'OTP',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'OTP',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'OTP',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'OTP',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',2,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BUD',2,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CRL',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CLJ',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CLJ',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CLJ',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CLJ',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'IBZ',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'IBZ',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'IBZ',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'IBZ',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'IBZ',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BMA',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BMA',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BMA',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BMA',1,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RAK',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RAK',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RAK',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'GDN',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'GDN',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'KTW',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'KTW',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'KTW',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'KTW',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'KTW',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'KTW',2,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ACE',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ACE',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ACE',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ACE',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,4,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,4,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LBA',1,4,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,4,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LTN',1,5,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MLA',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MLA',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MLA',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MLA',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MLA',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MLA',1,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MLA',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MLA',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LIN',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LIN',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LIN',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LIN',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LIN',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LIN',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LIN',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'LIN',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RBA',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RBA',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RBA',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RBA',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RBA',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,3,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,4,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,4,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',1,4,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',2,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',2,4,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',2,4,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',2,4,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ORY',2,4,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'POZ',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'POZ',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'POZ',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'POZ',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'POZ',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RNS',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RNS',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SDR',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SDR',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SDR',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SDR',1,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'TSR',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'TSR',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'IAS',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'IAS',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'VLL',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'VLL',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'VLL',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'VLL',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'VLL',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'WAW',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'WAW',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'WAW',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'WAW',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FUE',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FUE',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FUE',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SVQ',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SVQ',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SVQ',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',2,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MUC',2,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',3,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',3,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',3,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',3,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',3,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',3,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CIA',3,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'AMS',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'AMS',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'AMS',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'AMS',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'AMS',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'AMS',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'AMS',1,4,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SCQ',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SCQ',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'SCQ',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',2,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'FCO',3,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'VVO',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'VVO',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'VVO',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',1,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',1,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'ZRH',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'DUS',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'DUS',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'DUS',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'TNG',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'TNG',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'TNG',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'TNG',1,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BGY',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MAD',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MAD',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MAD',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MAD',3,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MAD',3,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MAD',3,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'MAD',3,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PRG',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PRG',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PRG',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PRG',2,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PRG',3,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PRG',3,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PRG',3,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RTM',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RTM',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RTM',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'RTM',1,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',3,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',3,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',3,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',3,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',3,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'JFK',3,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',2,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',2,2,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',2,2,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',2,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',2,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',3,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',3,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',3,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',3,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',3,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',3,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',3,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'PEK',3,3,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',1,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',1,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',1,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'BCN',2,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',1,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',1,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',1,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',1,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',1,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',2,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',2,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',2,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',2,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',2,3,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',2,3,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',2,3,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',3,1,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',3,1,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',3,1,3);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',3,1,4);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',3,2,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',3,2,2);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',3,3,1);

INSERT INTO PORTA_EMBARCAMENT ( CODI_AEROPORT, TERMINAL, AREA, PORTA) VALUES (
'CDG',3,3,2);

