INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA2159',TO_Date('25/07/2013','DD/MM/YYYY'),'AIR EUROPA','Airbus A330-300','BCN','ORY',1,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA2159',TO_Date('01/08/2013','DD/MM/YYYY'),'AIR EUROPA','Airbus A330-300','BCN','ORY',1,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA2159',TO_Date('08/08/2013','DD/MM/YYYY'),'AIR EUROPA','Airbus A330-300','BCN','ORY',1,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA2159',TO_Date('15/08/2013','DD/MM/YYYY'),'AIR EUROPA','Airbus A330-300','BCN','ORY',1,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA5453',TO_Date('25/07/2013','DD/MM/YYYY'),'AIR EUROPA','Boeing 737-800','ORY','JFK',2,4,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA5453',TO_Date('01/08/2013','DD/MM/YYYY'),'AIR EUROPA','Boeing 737-800','ORY','JFK',2,4,4);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA5453',TO_Date('08/08/2013','DD/MM/YYYY'),'AIR EUROPA','Boeing 737-800','ORY','JFK',2,4,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA5453',TO_Date('15/08/2013','DD/MM/YYYY'),'AIR EUROPA','Boeing 737-800','ORY','JFK',2,4,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA6159',TO_Date('02/06/2013','DD/MM/YYYY'),'AIR EUROPA','Embraer 145','BCN','RTM',2,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA6159',TO_Date('09/06/2013','DD/MM/YYYY'),'AIR EUROPA','Embraer 145','BCN','RTM',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR129',TO_Date('31/05/2013','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-800','BCN','RNS',1,2,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR1449',TO_Date('09/02/2014','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','BCN','ORY',1,3,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR1449',TO_Date('16/02/2014','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','BCN','ORY',2,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR1449',TO_Date('23/02/2014','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','BCN','ORY',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR4862',TO_Date('30/03/2013','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','BCN','ORY',1,2,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR4862',TO_Date('06/04/2013','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','BCN','ORY',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'ANS5390',TO_Date('07/11/2014','DD/MM/YYYY'),'AIR NOSTRUM','ATR-72-600','BCN','MLA',NULL,NULL,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AUA7308',TO_Date('14/11/2013','DD/MM/YYYY'),'AUSTRIAN AIRLINES','Airbus A320-201','BCN','PEK',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AZA075',TO_Date('21/08/2014','DD/MM/YYYY'),'ALITALIA COMPAGNIA AEREA ITALIANA SPA','Airbus A320-200','BCN','LIN',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AZA2404',TO_Date('14/01/2013','DD/MM/YYYY'),'ALITALIA COMPAGNIA AEREA ITALIANA SPA','Airbus A320-200','BCN','CIA',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'BER8937',TO_Date('11/10/2014','DD/MM/YYYY'),'AIR BERLIN INC.','Airbus A320-200','BCN','MUC',2,NULL,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'CSA691',TO_Date('21/09/2014','DD/MM/YYYY'),'CZECH AIRLINES','Airbus A320-200','BCN','PRG',1,1,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'DLH1819',TO_Date('05/04/2014','DD/MM/YYYY'),'LUFTHANSA','Airbus A320-200','BCN','DUS',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'DLH1819',TO_Date('12/04/2014','DD/MM/YYYY'),'LUFTHANSA','Airbus A320-200','BCN','DUS',1,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE0655',TO_Date('23/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A340-300','BCN','BJZ',2,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE0911',TO_Date('07/04/2014','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','IBZ',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2115',TO_Date('10/10/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','ACE',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2115',TO_Date('17/10/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','ACE',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2115',TO_Date('24/10/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','ACE',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2115',TO_Date('31/10/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','ACE',2,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2115',TO_Date('07/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','ACE',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2115',TO_Date('14/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','ACE',1,3,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2701',TO_Date('13/04/2014','DD/MM/YYYY'),'IBERIA','Airbus A340-600','BCN','MAD',1,3,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5348',TO_Date('22/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A319-100','BCN','VLL',1,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5393',TO_Date('30/03/2014','DD/MM/YYYY'),'IBERIA','Airbus A321-200','BCN','SDR',1,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5448',TO_Date('05/04/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','BCN','FUE',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5459',TO_Date('30/07/2014','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','SVQ',1,2,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5631',TO_Date('22/04/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','BCN','SCQ',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5644',TO_Date('09/09/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','BCN','ZRH',1,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5686',TO_Date('21/06/2014','DD/MM/YYYY'),'IBERIA','Airbus A321-200','BCN','BFS',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6401',TO_Date('09/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A319-100','BCN','RAK',1,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6755',TO_Date('14/03/2014','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','AMS',1,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6769',TO_Date('17/12/2013','DD/MM/YYYY'),'IBERIA','Airbus A330-300','BCN','VVO',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6825',TO_Date('04/09/2014','DD/MM/YYYY'),'IBERIA','Airbus A330-300','BCN','POZ',2,1,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6831',TO_Date('30/07/2013','DD/MM/YYYY'),'IBERIA','Airbus A340-300','BCN','BMA',2,1,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE7721',TO_Date('24/07/2014','DD/MM/YYYY'),'IBERIA','Airbus A340-300','BCN','ORY',2,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE7880',TO_Date('06/09/2013','DD/MM/YYYY'),'IBERIA','Airbus A340-600','BCN','LIN',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM1662',TO_Date('03/07/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 737-900','BCN','SXF',1,3,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM2699',TO_Date('04/07/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 737-900','SXF','PEK',3,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM4303',TO_Date('05/07/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 777-300ER','BCN','LIN',1,2,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RAM693',TO_Date('21/07/2013','DD/MM/YYYY'),'ROYAL AIR MAROC','Boeing 737-700','BCN','TNG',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RAM965',TO_Date('26/05/2014','DD/MM/YYYY'),'ROYAL AIR MAROC','Boeing 737-700','BCN','RBA',1,3,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6302',TO_Date('06/03/2013','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','BCN','LTN',1,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6332',TO_Date('16/04/2014','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','BCN','LBA',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6341',TO_Date('30/10/2013','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','BCN','BLQ',2,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6353',TO_Date('25/10/2013','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','BCN','CRL',1,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6396',TO_Date('30/04/2013','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','BCN','BUD',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1035',TO_Date('28/03/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','BCN','BGY',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1312',TO_Date('11/02/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','BCN','FCO',2,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1515',TO_Date('26/10/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','BCN','WAW',2,NULL,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1670',TO_Date('02/07/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A319-100','BCN','TSR',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1702',TO_Date('28/02/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A319-100','BCN','IAS',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG2111',TO_Date('20/08/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','BCN','POZ',2,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG2224',TO_Date('24/08/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','BCN','GDN',2,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG3508',TO_Date('21/12/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A319-100','BCN','KTW',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG8008',TO_Date('16/11/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A319-100','BCN','ORY',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'DLH1802',TO_Date('27/09/2013','DD/MM/YYYY'),'LUFTHANSA','Boeing 717','MUC','MAD',1,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE8375',TO_Date('06/09/2013','DD/MM/YYYY'),'IBERIA','Airbus A319-100','TNG','MAD',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE3231',TO_Date('12/08/2011','DD/MM/YYYY'),'IBERIA','Airbus A321-200','FCO','MAD',3,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6767',TO_Date('21/05/2012','DD/MM/YYYY'),'IBERIA','Airbus A321-200','BCN','MAD',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM2699',TO_Date('01/10/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 737-900','BCN','AMS',2,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM4303',TO_Date('01/10/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Airbus A330-300','AMS','PEK',1,4,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AF1213',TO_Date('19/10/2013','DD/MM/YYYY'),'AIR FRANCE','Airbus A318-100','LIN','CDG',1,2,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AF2356',TO_Date('20/10/2013','DD/MM/YYYY'),'AIR FRANCE','Boeing 777-300ER','CDG','OTP',3,1,4);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RO607 ',TO_Date('21/10/2013','DD/MM/YYYY'),'Tarom Romanian','ATR72','OTP','TSR',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IB5493 ',TO_Date('30/09/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','MLA','BCN',1,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IB5646 ',TO_Date('30/09/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-201','BCN','TNG',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IB3907 ',TO_Date('29/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','FUE','MAD',1,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM1708 ',TO_Date('30/11/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 737-800','MAD','AMS',3,1,4);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM4303 ',TO_Date('30/11/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Airbus A330-300','AMS','PEK',1,4,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA2195',TO_Date('31/07/2013','DD/MM/YYYY'),'AIR EUROPA','Airbus A330-300','ORY','BCN',2,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA2195',TO_Date('20/08/2013','DD/MM/YYYY'),'AIR EUROPA','Airbus A330-300','ORY','BCN',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA2195',TO_Date('24/08/2013','DD/MM/YYYY'),'AIR EUROPA','Airbus A330-300','ORY','BCN',2,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA2195',TO_Date('29/08/2013','DD/MM/YYYY'),'AIR EUROPA','Airbus A330-300','ORY','BCN',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA5454',TO_Date('05/08/2013','DD/MM/YYYY'),'AIR EUROPA','Boeing 737-800','JFK','ORY',3,2,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA5454',TO_Date('15/08/2013','DD/MM/YYYY'),'AIR EUROPA','Boeing 737-800','JFK','ORY',3,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA5454',TO_Date('27/08/2013','DD/MM/YYYY'),'AIR EUROPA','Boeing 737-800','JFK','ORY',3,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA5454',TO_Date('29/08/2013','DD/MM/YYYY'),'AIR EUROPA','Boeing 737-800','JFK','ORY',3,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA6159',TO_Date('13/06/2013','DD/MM/YYYY'),'AIR EUROPA','Embraer 145','RTM','BCN',1,1,4);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AEA6158',TO_Date('16/06/2013','DD/MM/YYYY'),'AIR EUROPA','Embraer 145','RTM','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR127',TO_Date('18/06/2013','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-800','RNS','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR1443',TO_Date('14/02/2014','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','ORY','BCN',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR1443',TO_Date('06/03/2014','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','ORY','BCN',2,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR1449',TO_Date('14/03/2014','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','ORY','BCN',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AFR4865',TO_Date('13/04/2013','DD/MM/YYYY'),'AIR FRANCE','Airbus A380-300','ORY','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'ANS5391',TO_Date('17/11/2014','DD/MM/YYYY'),'AIR NOSTRUM','ATR-72-600','MLA','BCN',NULL,NULL,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AUA7304',TO_Date('19/11/2013','DD/MM/YYYY'),'AUSTRIAN AIRLINES','Airbus A320-201','PEK','BCN',2,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AZA073',TO_Date('10/09/2014','DD/MM/YYYY'),'ALITALIA COMPAGNIA AEREA ITALIANA SPA','Airbus A320-200','LIN','BCN',1,1,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AZA2401',TO_Date('20/01/2013','DD/MM/YYYY'),'ALITALIA COMPAGNIA AEREA ITALIANA SPA','Airbus A320-200','CIA','BCN',1,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'BER8939',TO_Date('21/10/2014','DD/MM/YYYY'),'AIR BERLIN INC.','Airbus A320-200','MUC','BCN',2,NULL,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'CSA694',TO_Date('27/09/2014','DD/MM/YYYY'),'CZECH AIRLINES','Airbus A320-200','PRG','BCN',3,1,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'DLH1813',TO_Date('21/04/2014','DD/MM/YYYY'),'LUFTHANSA','Airbus A320-200','DUS','BCN',1,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'DLH1813',TO_Date('30/04/2014','DD/MM/YYYY'),'LUFTHANSA','Airbus A320-200','DUS','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE0651',TO_Date('10/12/2013','DD/MM/YYYY'),'IBERIA','Airbus A340-300','BJZ','BCN',1,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE0918',TO_Date('18/04/2014','DD/MM/YYYY'),'IBERIA','Airbus A320-200','IBZ','BCN',1,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2119',TO_Date('30/10/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','ACE','BCN',2,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2119',TO_Date('03/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','ACE','BCN',2,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2119',TO_Date('10/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','ACE','BCN',2,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2119',TO_Date('05/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','ACE','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2119',TO_Date('14/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','ACE','BCN',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2119',TO_Date('30/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','ACE','BCN',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE2700',TO_Date('26/04/2014','DD/MM/YYYY'),'IBERIA','Airbus A340-600','MAD','BCN',3,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5344',TO_Date('11/12/2013','DD/MM/YYYY'),'IBERIA','Airbus A319-100','VLL','BCN',1,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5390',TO_Date('12/04/2014','DD/MM/YYYY'),'IBERIA','Airbus A321-200','SDR','BCN',1,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5445',TO_Date('24/04/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','FUE','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5458',TO_Date('04/08/2014','DD/MM/YYYY'),'IBERIA','Airbus A320-200','SVQ','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5632',TO_Date('08/05/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','SCQ','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5643',TO_Date('15/09/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','ZRH','BCN',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE5685',TO_Date('05/07/2014','DD/MM/YYYY'),'IBERIA','Airbus A321-200','BFS','BCN',1,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6400',TO_Date('15/11/2013','DD/MM/YYYY'),'IBERIA','Airbus A319-100','RAK','BCN',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6752',TO_Date('30/03/2014','DD/MM/YYYY'),'IBERIA','Airbus A320-200','AMS','BCN',1,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6768',TO_Date('01/01/2014','DD/MM/YYYY'),'IBERIA','Airbus A330-300','VVO','BCN',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6826',TO_Date('20/09/2014','DD/MM/YYYY'),'IBERIA','Airbus A330-300','POZ','BCN',1,2,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6832',TO_Date('11/08/2013','DD/MM/YYYY'),'IBERIA','Airbus A340-300','BMA','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE7723',TO_Date('10/08/2014','DD/MM/YYYY'),'IBERIA','Airbus A340-300','ORY','BCN',1,2,4);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE7881',TO_Date('19/09/2013','DD/MM/YYYY'),'IBERIA','Airbus A340-600','LIN','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM1663',TO_Date('21/07/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 737-900','SXF','BCN',3,4,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM2693',TO_Date('10/07/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 737-900','PEK','SXF',1,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM4302',TO_Date('15/07/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 777-300ER','LIN','BCN',1,2,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RAM692',TO_Date('09/08/2013','DD/MM/YYYY'),'ROYAL AIR MAROC','Boeing 737-700','TNG','BCN',1,1,4);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RAM964',TO_Date('02/06/2014','DD/MM/YYYY'),'ROYAL AIR MAROC','Boeing 737-700','RBA','BCN',1,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6304',TO_Date('15/03/2013','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','LTN','BCN',1,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6337',TO_Date('27/04/2014','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','LBA','BCN',1,4,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6346',TO_Date('08/11/2013','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','BLQ','BCN',2,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6355',TO_Date('30/10/2013','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','CRL','BCN',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RYR6393',TO_Date('10/05/2013','DD/MM/YYYY'),'RYANAIR','Boeing 737-800','BUD','BCN',2,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1032',TO_Date('07/04/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','BGY','BCN',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1316',TO_Date('28/02/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','FCO','BCN',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1514',TO_Date('04/11/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','WAW','BCN',NULL,NULL,NULL);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1678',TO_Date('21/07/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A319-100','TSR','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG1701',TO_Date('17/02/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A319-100','IAS','BCN',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG2117',TO_Date('27/08/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','POZ','BCN',1,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG2222',TO_Date('29/08/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A320-200','GDN','BCN',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG3501',TO_Date('08/01/2014','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A319-100','KTW','BCN',2,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'VLG8003',TO_Date('03/12/2013','DD/MM/YYYY'),'VUELING AIRLINES','Airbus A319-100','ORY','BCN',1,3,4);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'DLH1807',TO_Date('04/10/2013','DD/MM/YYYY'),'LUFTHANSA','Boeing 717','MAD','MUC',3,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE8379',TO_Date('15/09/2013','DD/MM/YYYY'),'IBERIA','Airbus A319-100','MAD','TNG',3,1,4);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE3235',TO_Date('20/08/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','MAD','FCO',3,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IBE6764',TO_Date('28/05/2012','DD/MM/YYYY'),'IBERIA','Airbus A321-200','MAD','BCN',3,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM2698',TO_Date('10/10/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 737-900','AMS','BCN',1,2,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM4304',TO_Date('09/10/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Airbus A330-300','PEK','AMS',3,3,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AF1215',TO_Date('01/11/2013','DD/MM/YYYY'),'AIR FRANCE','Airbus A318-100','CDG','LIN',2,3,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'AF2352',TO_Date('31/10/2013','DD/MM/YYYY'),'AIR FRANCE','Boeing 777-300ER','OTP','CDG',1,1,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'RO604',TO_Date('08/11/2013','DD/MM/YYYY'),'Tarom Romanian','ATR72','TSR','OTP',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IB5492',TO_Date('10/10/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-200','BCN','MLA',1,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IB5648',TO_Date('07/10/2013','DD/MM/YYYY'),'IBERIA','Airbus A320-201','TNG','BCN',1,1,1);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'IB3907 ',TO_Date('13/12/2013','DD/MM/YYYY'),'IBERIA','Airbus A321-200','MAD','FUE',3,1,2);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM1709',TO_Date('13/12/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Boeing 737-800','AMS','MAD',1,2,3);

INSERT INTO VOL ( CODI_VOL, DATA, COMPANYIA, TIPUS_AVIO, ORIGEN, DESTINACIO, TERMINAL, AREA, PORTA) VALUES (
'KLM4302',TO_Date('13/12/2013','DD/MM/YYYY'),'K.L.M. ROYAL DUTCH AIRLINES','Airbus A330-300','PEK','AMS',1,3,1);

